services:

  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html

  database:
    container_name: database
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=250M
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      USER: 1000
    volumes:
      - ./sql-data:/var/lib/mysql
    ports:
      - ${DB_EXPOSED_PORT}:3306

  php-myadmin:
    container_name: phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 6G
    depends_on:
      - database